version: 2.1

orbs:
  build-tools: circleci/build-tools@2.7.0
  doctl: digitalocean/cli@0.1.1
  k8s: digitalocean/k8s@0.1.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - doctl/install
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            make build
      - run:
          name: Push to DigitialOcean registry
          command: |
            doctl registry login
            make push
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - k8s/install
      - k8s/initialize:
          cluster: ${CLUSTER_NAME}
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Deploy
          command: |
            make deploy
workflows:
  version: 2
  build-master:
    jobs:
      - build
      - deploy:
          requires:
            - build