apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etrade-token-fetcher
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: token-fetcher
            image: registry.digitalocean.com/options-cash/etrade-token-fetcher:$CIRCLE_SHA1
            imagePullPolicy: Always
            command: ["./run.sh"]
            envFrom:
            - configMapRef:
               name: etrade-config
            volumeMounts:
            - mountPath: /tokens
              name: token-volume
          restartPolicy: OnFailure
          volumes:
            - name: token-volume
              persistentVolumeClaim:
                claimName: token-pvc        